// export const BOOLEAN_LIST = [{value: true, label: 'Yes'}, {value: false, label: 'No'}];
// export const ITEM_QUANTITY_TYPE = ['piece', 'kg', 'gram', 'gallon', 'quart', 'ltr', 'ml'];
// export const METER_READING = ['miles', 'km', 'hours'];
// export const VEHICLE_STATUS = [
//     {value: 'available', label: 'Available'},
//     {value: 'in_maintenance', label: 'In Maintenance'},
//     {value: 'maintenance_required', label: 'Maintenance Required'},
//     {value: 'breakdown', label: 'Breakdown'},
//     {value: 'discontinue', label: 'Discontinue'}
// ];
// export const PRIORITY = ['normal', 'low', 'medium', 'high', 'emergency'];
// export const TRIP_STATUS = [
//     {label: 'Trip is not started', value: 'not_started'},
//     {label: 'In-Progress', value: 'in_progress'},
//     {label: 'Completed', value: 'completed'},
//     {label: 'Cancelled', value: 'cancelled'}
// ];
// export const POD_STATUS = [
//     {value: 'awaited', label: 'Load completed - Awaiting POD pack'},
//     {value: 'in_progress', label: 'In-Progress'},
//     {value: 'incomplete', label: 'POD pack received - Incomplete'},
//     {value: 'received', label: 'POD pack received - In Full'},
//     {value: 'cancelled', label: 'Lead Cancelled'}
// ];
// export const POD_STATUS_EMPTY_LEG = [
//     {value: 'empty_leg', label: 'Empty Leg'}
// ];
// export const FAULT_TYPE = ['repair', 'replace'];
// export const TOOL_STATUS = [
//     {value: 'available', label: 'Available'},
//     {value: 'unavailable', label: 'Not Available'},
//     {value: 'in_maintenance', label: 'In Maintenance'},
//     {value: 'out_of_service', label: 'Out Of Service'}
// ];
// export const WORKORDER_TYPE = [
//     'general',
//     'preventive',
//     'breakdown',
//     'corrective',
//     'safety',
//     'upgrade',
//     'cleaning',
//     'testing',
//     'project',
//     'electrical',
//     'inspection',
//     'calibration',
//     'other'
// ];
// export const TASK_STATUS = [
//     {label: 'Initiated', value: 'initiated'},
//     {label: 'In-Progress', value: 'in_progress'},
//     {label: 'On Hold', value: 'on_hold'},
//     {label: 'Completed', value: 'completed'}
// ]
// export const CONGESTION_SEVERITY = ['average', 'bad', 'excessive'];
// export const MEMBER_ROLE = [
//     {value: 'admin', label: 'Admin'},
//     {value: 'driver', label: 'Driver'},
//     {value: 'route_planner', label: 'Route Planner'},
//     {value: 'route_operations', label: 'Route Operation'},
//     {value: 'finance', label: 'Finance'},
//     {value: 'supplier', label: 'Supplier'},
//     {value: 'mechanic', label: 'Mechanic'}
// ];
// export const ADDRESS_TYPE = [
//     {value: 'stoppage', label: 'Truck Stop'},
//     {value: 'fuel', label: 'Fuel Station'},
//     {value: 'washing', label: 'Washing Station'},
//     {value: 'service_provider', label: 'Service Provider'},
//     {value: 'service_dealership', label: 'Service Dealership'},
//     {value: 'loading', label: 'Loading Point'},
//     {value: 'off_loading', label: 'Off Loading Point'},
//     {value: 'rest', label: 'Authorized Rest Point'},
//     {value: 'tyre_change', label: 'Tyre Point'}
// ];
// export const EMPLOYMENT_STATUS = [
//     {value: 'active', label: 'Active', id: 0},
//     {value: 'inactive', label: 'In Active', id: 1}
// ];
// export const INSPECTION_FORM_FIELD_TYPE = [
//     {value: 'good_repair_replace', label: 'Good-Repair-Replace-NA'},
//     {value: 'yes_no_na', label: 'Yes-No-NA'},
//     {value: 'pass_fail_na', label: 'Pass-Fail-NA'},
//     {value: 'ok_faulty_na', label: 'Ok-Faulty-NA'},
//     {value: 'text_field', label: 'Textfield'},
//     {value: 'number', label: 'Number'}
// ];
// export const INSPECTION_REPORT_CONDITION = [
//     {value: 'excellent_condition', label: 'Excellent Condition'},
//     {value: 'good_condition', label: 'Good Condition'},
//     {value: 'little_wear', label: 'A little wear'},
//     {value: 'minor_repair_required', label: 'Minor Repair required'},
//     {value: 'major_repair_required', label: 'Major Repair required'},
//     {value: 'cannot_determine', label: 'Cannot determine'},
//     {value: 'na', label: 'Not Applicable'}
// ];

// export const COUNTRIES = [
//     {label: 'Afghanistan', value: 'AF'},
//     {label: 'Åland Islands', value: 'AX'},
//     {label: 'Albania', value: 'AL'},
//     {label: 'Algeria', value: 'DZ'},
//     {label: 'American Samoa', value: 'AS'},
//     {label: 'AndorrA', value: 'AD'},
//     {label: 'Angola', value: 'AO'},
//     {label: 'Anguilla', value: 'AI'},
//     {label: 'Antarctica', value: 'AQ'},
//     {label: 'Antigua and Barbuda', value: 'AG'},
//     {label: 'Argentina', value: 'AR'},
//     {label: 'Armenia', value: 'AM'},
//     {label: 'Aruba', value: 'AW'},
//     {label: 'Australia', value: 'AU'},
//     {label: 'Austria', value: 'AT'},
//     {label: 'Azerbaijan', value: 'AZ'},
//     {label: 'Bahamas', value: 'BS'},
//     {label: 'Bahrain', value: 'BH'},
//     {label: 'Bangladesh', value: 'BD'},
//     {label: 'Barbados', value: 'BB'},
//     {label: 'Belarus', value: 'BY'},
//     {label: 'Belgium', value: 'BE'},
//     {label: 'Belize', value: 'BZ'},
//     {label: 'Benin', value: 'BJ'},
//     {label: 'Bermuda', value: 'BM'},
//     {label: 'Bhutan', value: 'BT'},
//     {label: 'Bolivia', value: 'BO'},
//     {label: 'Bosnia and Herzegovina', value: 'BA'},
//     {label: 'Botswana', value: 'BW'},
//     {label: 'Bouvet Island', value: 'BV'},
//     {label: 'Brazil', value: 'BR'},
//     {label: 'British Indian Ocean Territory', value: 'IO'},
//     {label: 'Brunei Darussalam', value: 'BN'},
//     {label: 'Bulgaria', value: 'BG'},
//     {label: 'Burkina Faso', value: 'BF'},
//     {label: 'Burundi', value: 'BI'},
//     {label: 'Cambodia', value: 'KH'},
//     {label: 'Cameroon', value: 'CM'},
//     {label: 'Canada', value: 'CA'},
//     {label: 'Cape Verde', value: 'CV'},
//     {label: 'Cayman Islands', value: 'KY'},
//     {label: 'Central African Republic', value: 'CF'},
//     {label: 'Chad', value: 'TD'},
//     {label: 'Chile', value: 'CL'},
//     {label: 'China', value: 'CN'},
//     {label: 'Christmas Island', value: 'CX'},
//     {label: 'Cocos (Keeling) Islands', value: 'CC'},
//     {label: 'Colombia', value: 'CO'},
//     {label: 'Comoros', value: 'KM'},
//     {label: 'Congo', value: 'CG'},
//     {label: 'Congo, The Democratic Republic of the', value: 'CD'},
//     {label: 'Cook Islands', value: 'CK'},
//     {label: 'Costa Rica', value: 'CR'},
//     {label: 'Cote D\'Ivoire', value: 'CI'},
//     {label: 'Croatia', value: 'HR'},
//     {label: 'Cuba', value: 'CU'},
//     {label: 'Cyprus', value: 'CY'},
//     {label: 'Czech Republic', value: 'CZ'},
//     {label: 'Denmark', value: 'DK'},
//     {label: 'Djibouti', value: 'DJ'},
//     {label: 'Dominica', value: 'DM'},
//     {label: 'Dominican Republic', value: 'DO'},
//     {label: 'Ecuador', value: 'EC'},
//     {label: 'Egypt', value: 'EG'},
//     {label: 'El Salvador', value: 'SV'},
//     {label: 'Equatorial Guinea', value: 'GQ'},
//     {label: 'Eritrea', value: 'ER'},
//     {label: 'Estonia', value: 'EE'},
//     {label: 'Ethiopia', value: 'ET'},
//     {label: 'Falkland Islands (Malvinas)', value: 'FK'},
//     {label: 'Faroe Islands', value: 'FO'},
//     {label: 'Fiji', value: 'FJ'},
//     {label: 'Finland', value: 'FI'},
//     {label: 'France', value: 'FR'},
//     {label: 'French Guiana', value: 'GF'},
//     {label: 'French Polynesia', value: 'PF'},
//     {label: 'French Southern Territories', value: 'TF'},
//     {label: 'Gabon', value: 'GA'},
//     {label: 'Gambia', value: 'GM'},
//     {label: 'Georgia', value: 'GE'},
//     {label: 'Germany', value: 'DE'},
//     {label: 'Ghana', value: 'GH'},
//     {label: 'Gibraltar', value: 'GI'},
//     {label: 'Greece', value: 'GR'},
//     {label: 'Greenland', value: 'GL'},
//     {label: 'Grenada', value: 'GD'},
//     {label: 'Guadeloupe', value: 'GP'},
//     {label: 'Guam', value: 'GU'},
//     {label: 'Guatemala', value: 'GT'},
//     {label: 'Guernsey', value: 'GG'},
//     {label: 'Guinea', value: 'GN'},
//     {label: 'Guinea-Bissau', value: 'GW'},
//     {label: 'Guyana', value: 'GY'},
//     {label: 'Haiti', value: 'HT'},
//     {label: 'Heard Island and Mcdonald Islands', value: 'HM'},
//     {label: 'Holy See (Vatican City State)', value: 'VA'},
//     {label: 'Honduras', value: 'HN'},
//     {label: 'Hong Kong', value: 'HK'},
//     {label: 'Hungary', value: 'HU'},
//     {label: 'Iceland', value: 'IS'},
//     {label: 'India', value: 'IN'},
//     {label: 'Indonesia', value: 'ID'},
//     {label: 'Iran, Islamic Republic Of', value: 'IR'},
//     {label: 'Iraq', value: 'IQ'},
//     {label: 'Ireland', value: 'IE'},
//     {label: 'Isle of Man', value: 'IM'},
//     {label: 'Israel', value: 'IL'},
//     {label: 'Italy', value: 'IT'},
//     {label: 'Jamaica', value: 'JM'},
//     {label: 'Japan', value: 'JP'},
//     {label: 'Jersey', value: 'JE'},
//     {label: 'Jordan', value: 'JO'},
//     {label: 'Kazakhstan', value: 'KZ'},
//     {label: 'Kenya', value: 'KE'},
//     {label: 'Kiribati', value: 'KI'},
//     {label: 'Korea, Democratic People\'S Republic of', value: 'KP'},
//     {label: 'Korea, Republic of', value: 'KR'},
//     {label: 'Kuwait', value: 'KW'},
//     {label: 'Kyrgyzstan', value: 'KG'},
//     {label: 'Lao People\'S Democratic Republic', value: 'LA'},
//     {label: 'Latvia', value: 'LV'},
//     {label: 'Lebanon', value: 'LB'},
//     {label: 'Lesotho', value: 'LS'},
//     {label: 'Liberia', value: 'LR'},
//     {label: 'Libyan Arab Jamahiriya', value: 'LY'},
//     {label: 'Liechtenstein', value: 'LI'},
//     {label: 'Lithuania', value: 'LT'},
//     {label: 'Luxembourg', value: 'LU'},
//     {label: 'Macao', value: 'MO'},
//     {label: 'Macedonia, The Former Yugoslav Republic of', value: 'MK'},
//     {label: 'Madagascar', value: 'MG'},
//     {label: 'Malawi', value: 'MW'},
//     {label: 'Malaysia', value: 'MY'},
//     {label: 'Maldives', value: 'MV'},
//     {label: 'Mali', value: 'ML'},
//     {label: 'Malta', value: 'MT'},
//     {label: 'Marshall Islands', value: 'MH'},
//     {label: 'Martinique', value: 'MQ'},
//     {label: 'Mauritania', value: 'MR'},
//     {label: 'Mauritius', value: 'MU'},
//     {label: 'Mayotte', value: 'YT'},
//     {label: 'Mexico', value: 'MX'},
//     {label: 'Micronesia, Federated States of', value: 'FM'},
//     {label: 'Moldova, Republic of', value: 'MD'},
//     {label: 'Monaco', value: 'MC'},
//     {label: 'Mongolia', value: 'MN'},
//     {label: 'Montserrat', value: 'MS'},
//     {label: 'Morocco', value: 'MA'},
//     {label: 'Mozambique', value: 'MZ'},
//     {label: 'Myanmar', value: 'MM'},
//     {label: 'Namibia', value: 'NA'},
//     {label: 'Nauru', value: 'NR'},
//     {label: 'Nepal', value: 'NP'},
//     {label: 'Netherlands', value: 'NL'},
//     {label: 'Netherlands Antilles', value: 'AN'},
//     {label: 'New Caledonia', value: 'NC'},
//     {label: 'New Zealand', value: 'NZ'},
//     {label: 'Nicaragua', value: 'NI'},
//     {label: 'Niger', value: 'NE'},
//     {label: 'Nigeria', value: 'NG'},
//     {label: 'Niue', value: 'NU'},
//     {label: 'Norfolk Island', value: 'NF'},
//     {label: 'Northern Mariana Islands', value: 'MP'},
//     {label: 'Norway', value: 'NO'},
//     {label: 'Oman', value: 'OM'},
//     {label: 'Pakistan', value: 'PK'},
//     {label: 'Palau', value: 'PW'},
//     {label: 'Palestinian Territory, Occupied', value: 'PS'},
//     {label: 'Panama', value: 'PA'},
//     {label: 'Papua New Guinea', value: 'PG'},
//     {label: 'Paraguay', value: 'PY'},
//     {label: 'Peru', value: 'PE'},
//     {label: 'Philippines', value: 'PH'},
//     {label: 'Pitcairn', value: 'PN'},
//     {label: 'Poland', value: 'PL'},
//     {label: 'Portugal', value: 'PT'},
//     {label: 'Puerto Rico', value: 'PR'},
//     {label: 'Qatar', value: 'QA'},
//     {label: 'Reunion', value: 'RE'},
//     {label: 'Romania', value: 'RO'},
//     {label: 'Russian Federation', value: 'RU'},
//     {label: 'RWANDA', value: 'RW'},
//     {label: 'Saint Helena', value: 'SH'},
//     {label: 'Saint Kitts and Nevis', value: 'KN'},
//     {label: 'Saint Lucia', value: 'LC'},
//     {label: 'Saint Pierre and Miquelon', value: 'PM'},
//     {label: 'Saint Vincent and the Grenadines', value: 'VC'},
//     {label: 'Samoa', value: 'WS'},
//     {label: 'San Marino', value: 'SM'},
//     {label: 'Sao Tome and Principe', value: 'ST'},
//     {label: 'Saudi Arabia', value: 'SA'},
//     {label: 'Senegal', value: 'SN'},
//     {label: 'Serbia and Montenegro', value: 'CS'},
//     {label: 'Seychelles', value: 'SC'},
//     {label: 'Sierra Leone', value: 'SL'},
//     {label: 'Singapore', value: 'SG'},
//     {label: 'Slovakia', value: 'SK'},
//     {label: 'Slovenia', value: 'SI'},
//     {label: 'Solomon Islands', value: 'SB'},
//     {label: 'Somalia', value: 'SO'},
//     {label: 'South Africa', value: 'ZA'},
//     {label: 'South Georgia and the South Sandwich Islands', value: 'GS'},
//     {label: 'Spain', value: 'ES'},
//     {label: 'Sri Lanka', value: 'LK'},
//     {label: 'Sudan', value: 'SD'},
//     {label: 'Suriname', value: 'SR'},
//     {label: 'Svalbard and Jan Mayen', value: 'SJ'},
//     {label: 'Swaziland', value: 'SZ'},
//     {label: 'Sweden', value: 'SE'},
//     {label: 'Switzerland', value: 'CH'},
//     {label: 'Syrian Arab Republic', value: 'SY'},
//     {label: 'Taiwan, Province of China', value: 'TW'},
//     {label: 'Tajikistan', value: 'TJ'},
//     {label: 'Tanzania, United Republic of', value: 'TZ'},
//     {label: 'Thailand', value: 'TH'},
//     {label: 'Timor-Leste', value: 'TL'},
//     {label: 'Togo', value: 'TG'},
//     {label: 'Tokelau', value: 'TK'},
//     {label: 'Tonga', value: 'TO'},
//     {label: 'Trinidad and Tobago', value: 'TT'},
//     {label: 'Tunisia', value: 'TN'},
//     {label: 'Turkey', value: 'TR'},
//     {label: 'Turkmenistan', value: 'TM'},
//     {label: 'Turks and Caicos Islands', value: 'TC'},
//     {label: 'Tuvalu', value: 'TV'},
//     {label: 'Uganda', value: 'UG'},
//     {label: 'Ukraine', value: 'UA'},
//     {label: 'United Arab Emirates', value: 'AE'},
//     {label: 'United Kingdom', value: 'GB'},
//     {label: 'United States', value: 'US'},
//     {label: 'United States Minor Outlying Islands', value: 'UM'},
//     {label: 'Uruguay', value: 'UY'},
//     {label: 'Uzbekistan', value: 'UZ'},
//     {label: 'Vanuatu', value: 'VU'},
//     {label: 'Venezuela', value: 'VE'},
//     {label: 'Viet Nam', value: 'VN'},
//     {label: 'Virgin Islands, British', value: 'VG'},
//     {label: 'Virgin Islands, U.S.', value: 'VI'},
//     {label: 'Wallis and Futuna', value: 'WF'},
//     {label: 'Western Sahara', value: 'EH'},
//     {label: 'Yemen', value: 'YE'},
//     {label: 'Zambia', value: 'ZM'},
//     {label: 'Zimbabwe', value: 'ZW'}
// ];

export const PROJECT_STATUS = [
    {label: 'Draft', value: 'draft'},
    {label: 'Active', value: 'active'},
    {label: 'Closed', value: 'closed'},
];